let validator = require("validator");
let createError = require('http-errors');
let shortid = require('shortid');

let { invalidRes } = require('../config');
let i, flag;

//checking same origin of request and https protocol
const checkURLDetailsPage = (req, res, next)=>{
	invalidRes.data = "Invalid host OR Insecure protcols";
	console.log(req.protocol, req.hostname);
	if (process.env.NODE_ENV === 'PRODUCTION'){
		((req.protocol === "https") && (req.hostname === "www.mrnotes.me" || req.host === "mrnote.herokuapp.com")) ? next():next(createError(505));
	}else
		next();
};

//checking same origin of request and https protocol
const checkURLDetailsJSON = (req, res, next)=>{
	invalidRes.data = "Invalid host OR Insecure protcols";
	console.log(req.protocol, req.hostname);
	if (process.env.NODE_ENV === 'PRODUCTION'){
		((req.protocol === "https") && (req.hostname === "www.mrnotes.me" || req.host === "mrnote.herokuapp.com")) ? next():res.status(505).json(invalidRes);
	}else
		next();
};

//data validation of login or signup page 
const bodyDataValidCred = (req, res, next)=>{
	for (i in req.body){
		if (req.body[`${i}`] == ('' || null) || (i == "email" && !validator.isEmail(req.body[`${i}`]))) {
			res.status(302).redirect(`${req.path}/?q=Invalid User Details`);
			flag = false;
			break;
		} 
	}
	if(flag){
		flag = true;
		next();
	}
}; 

/**
 * This function will check any value isn't null recevied in body part of request
 * @param {Object} req.body
 * @param {Object} res
 * @param {function} next
 *  */
const bodyDataValidJSON = (req, res, next)=>{
	for(i in req.body){
		tempStore = req.body[`${i}`];
		//trim data
		req.body[`${i}`] = (typeof(tempStore)=="string")? tempStore.trim():tempStore;

		//checking if the field is not empty
		if(req.body[`${i}`] == ('' || null)){
			invalidRes.data = "INVALID DATA";
			return res.json(invalidRes);
		}
	}
	next();
}; 

//uid validation generated by shortid
const validId = (req, res, next) => {
	flag = true;
	//console.log(req.params);
	for(i in req.params){
		//console.log(shortid.isValid(req.params[`${i}`]), req.params[`${i}`]);
		flag = (shortid.isValid(req.params[`${i}`])) ? true: false;
	}
	//console.log(flag);
	flag ? next():res.json(invalidRes);
};


module.exports = { bodyDataValidCred, bodyDataValidJSON, validId, checkURLDetailsPage,
	 checkURLDetailsJSON };